// <auto-generated />
using AuditBenchmarkModule.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuditBenchmarkModule.Migrations
{
    [DbContext(typeof(BenchmarkDBContext))]
    [Migration("20220726210321_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuditBenchmarkModule.Models.AuditBenchmark", b =>
                {
                    b.Property<string>("auditType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("benchmarkNoAnswers")
                        .HasColumnType("int");

                    b.HasKey("auditType");

                    b.ToTable("AuditBenchmarkList");
                });
#pragma warning restore 612, 618
        }
    }
}
